/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -p dbus/mprisroot dbus/org.mpris.MediaPlayer2.xml
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbus/mprisroot.h"

/*
 * Implementation of interface class OrgMprisMediaPlayer2Interface
 */

OrgMprisMediaPlayer2Interface::OrgMprisMediaPlayer2Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgMprisMediaPlayer2Interface::~OrgMprisMediaPlayer2Interface()
{
}


#include "dbus/mprisroot.moc"
